version: 2
defaults: &defaults
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
  working_directory: ~/repo
restore_ruby_cache: &restore_ruby_cache
  restore_cache:
    keys:
      - v2-dependencies-{{ checksum "Gemfile.lock" }}
      - v2-dependencies-
setup_rubygems: &setup_rubygems
  run:
    name: Add RubyGems API key
    command: |
      mkdir -p ~/.gem
      echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
      chmod 0600 ~/.gem/credentials

install_dependencies: &install_dependencies
  run:
    name: Install Dependencies
    command: |
      gem update --system
      gem install bundler -v 2.1.4
      bundle install --jobs=4 --retry=3 --path vendor/bundle

save_ruby_cache: &save_ruby_cache
  save_cache:
    paths:
      - ./vendor/bundle
    key: v1-dependencies-{{ checksum "Gemfile.lock" }}
download_cc_reporter: &download_cc_reporter
  run:
    name: Download Code Climate Test Reporter
    command: |
      mkdir -p tmp/
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
      chmod +x ./tmp/cc-test-reporter




persist: &persist
  persist_to_workspace:
    root: tmp
    paths:
      - cc-test-reporter
run_rspec_tests: &run_rspec_tests
  run:
    name: Run RSpec Tests
    command: |
      mkdir /tmp/test-results
      ./tmp/cc-test-reporter before-build
      TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
        circleci tests split --split-by=timings)"

      bundle exec rspec --format progress \
                        --format RspecJunitFormatter \
                        --out /tmp/test-results/rspec.xml \
                        --format progress \
                        $TEST_FILES
      ./tmp/cc-test-reporter format-coverage -t simplecov -o "tmp/codeclimate.json"



upload_coverage: &upload_coverage
  run:
    name: Upload Coverage
    command: |
      ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.json

release_rubygem: &release_rubygem
  run:
    name: Release new version to RubyGems
    command: |
      bundle exec rake release

jobs:
  rspec-tests:
    <<: *defaults
    steps:
      - checkout
      - *restore_ruby_cache
      - *install_dependencies
      - *save_ruby_cache
      - *download_cc_reporter
      - *persist
      - *run_rspec_tests
      - *upload_coverage
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  release:
    <<: *defaults
    steps:
      - checkout
      - *restore_ruby_cache
      - *setup_rubygems
      - *install_dependencies
      - *save_ruby_cache
      - *release_rubygem

workflows:
  version: 2
  commit:
    jobs:
      - rspec-tests
      - release:
          requires:
            - rspec-tests
          filters:
            branches:
              only:
                - master
